### ISSUE TITLE
How to suggest new xp card design ?

### ISSUE THREAD

**Issue by BastLast** [ZRunner/Axobot#49]
I wanted to suggest a DraftBot xp card design but those assets seems to be private. How to suggest new one ? 
![image](https://user-images.githubusercontent.com/38099970/223685092-3192349c-8893-4910-bbee-6097dcea96eb.png)

**Comment by BastLast** [comment]
also, could be cool as a server owner to have the ability to override user settings but I think this suggestion is way harder to implement and will be put in the already way too long backlog xD

**Comment by ZRunner** [comment]
Server-wide rank cards are not planned in the near future, I don't know yet which card (between server and user) should take precedence.

On the other hand I've been working for a while on a new xp card generator, with the long term goal of allowing anyone to create their own card, a bit like the mee6 system. 

Until then, I'm not opposed to adding a special Draftbot style that users could collect, I suggest you get in touch with Adri to see how he generated the current maps.
